### ISSUE TITLE
Protected-Page and API are still accessible after logout from identity server!

### ISSUE THREAD

**Issue by amirpourya** [scottbrady91/Angular4-OidcClientJs-Example#10]
Protected-Page and API are still accessible after logging out from identity server!

Any Ideas or solutions? :)

**Comment by scottbrady91** [comment]
Sounds like your app is not cleaning out it's storage. Unless you mean you want SSOff?

**Comment by priyank89patel** [comment]
@amirpourya I think you will need to add `logout()` method in the `auth.service.ts` file and call it from the client instead of directly signing out from identity server.
`logout(): void {
    this.manager.signoutRedirect();
  }`
