### ISSUE TITLE
could not complete authentication: Error: Unauthorized (401) - IE Browser Windows 7

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [scottbrady91/Angular4-OidcClientJs-Example#5]
Hi All,

We are facing the could not complete the authentication: Error: Unauthorized (401) in IE browser window 7 OS.

The IE Browser version is IE Edge.

could not complete authentication: Error: Unauthorized (401)
ERROR Error: Uncaught (in promise): TypeError: Unable to get property 'profile' of undefined or null reference
TypeError: Unable to get property 'profile' of undefined or null reference

**Comment by scottbrady91** [comment]
Sorry, I'm in the enviable position of having no experience with IE
