### ISSUE TITLE
get new access token without redirect to authorization endpoint

### ISSUE THREAD

**Issue by meysam7289** [scottbrady91/Angular4-OidcClientJs-Example#7]
How do I get a new Token from Token Endpoint after expiration of the token without going to the Authorization Endpoint and then redirect to Callback Endpoint?
(so that the user does not understand it)

**Comment by scottbrady91** [comment]
Check out silent refresh. This works for both implicit and authorization code flows: https://www.scottbrady91.com/OpenID-Connect/Silent-Refresh-Refreshing-Access-Tokens-when-using-the-Implicit-Flow
