### ISSUE TITLE
user object not reset when complete silent refresh

### ISSUE THREAD

**Issue by meysam7289** [scottbrady91/Angular4-OidcClientJs-Example#9]
hi, I implemented silent refresh operation in this project, but after each silent refresh operation, the user object in `auth service` is not set to the new information, which causes the problem in `isLoggedIn` and `getAuthorizationHeaderValue `function.
How to set the user object from `silent-refresh.html` file?

**Comment by scottbrady91** [comment]
As far as I remember, the silent refresh stuff is outside of the context of the Angular app and will update the user entry in storage.

When getting the user, the auth service should then be calling oidc-client get user method, which simply loads the user entry in storage.

So, I'm not sure why it wouldn't be working. Sorry.

Feel free to share your solution if it needs to be added to this sample code!
